all:
	g++ -std=c++17 DG_Miner.cpp -lstdc++fs -o DG_Miner

test:
	./DG_Miner ../database/test/test.simpoint_weight ../database/test/test ../database/test/test.pc_mem_trace result_trace.txt 10 0 2 100 2 10
